#!/usr/bin/env bash

ANSI_NO_COLOR='\033[0m'
ANSI_COLOR_RED='\033[0;31m'
ANSI_COLOR_GREEN='\033[0;32m'
ANSI_COLOR_ORANGE='\033[0;33m'
ANSI_COLOR_YELLOW='\033[1;33m'
ANSI_COLOR_BLUE='\033[0;34m'
ANSI_COLOR_LIGHT_BLUE='\033[1;34m'

success() {
    printf "${ANSI_COLOR_GREEN}$*${ANSI_NO_COLOR}"
}
warning() {
    printf "${ANSI_COLOR_ORANGE}$*${ANSI_NO_COLOR}"
}
error() {
    printf "${ANSI_COLOR_RED}$*${ANSI_NO_COLOR}"
}
highlight() {
    printf "${ANSI_COLOR_LIGHT_BLUE}$*${ANSI_NO_COLOR}"
}
text() {
    printf "${ANSI_NO_COLOR}$*"
}
title() {
    echo ""
    echo ""
    echo -e "${ANSI_COLOR_YELLOW}$*${ANSI_NO_COLOR}"
    echo -e "${ANSI_COLOR_YELLOW}----------------------------------------------------------------${ANSI_NO_COLOR}"
    echo ""
}
yell() {
    echo -e "$0: ${ANSI_COLOR_RED}$*${ANSI_NO_COLOR}" >&2;
}
